export const NAVIGATION_KIND = {
  BROWSER_NAVIGATION: 'BROWSER_NAVIGATION',
  ROUTER_PUSH: 'ROUTER_PUSH',
};

export const APP_ACTION = {
  ...NAVIGATION_KIND,
  SERVER_ACTION: 'SERVER_ACTION',
  REMOVE_FLASH_MESSAGE: 'REMOVE_FLASH_MESSAGE',
};
